version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_b12
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_b12
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter_b12
    ports:
      - "9100:9100"
