version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres_b11
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    container_name: adminer_b11
    ports:
      - "8083:8080"
    depends_on:
      - postgres
